---
display_name: My Custom Dosing Automation
automation_name: my_custom_dosing_automation
fields:
  - key: duration
    default: 20
    unit: min
    label: Duration between events
  - key: volume
    default: 0.5
    unit: mL
    label: Max volume
